### ISSUE TITLE
How to include Foxlight in an app?

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foxlight#11]
:hamster: 

I'm trying to apply Foxlight to an React app and wondering what the best way is to include it.

Currently I just 
- npm install it
- add `@import './node_modules/foxlight/src/scss/foxlight.scss';` in the `index.scss` file in my app
- use https://www.npmjs.com/package/node-sass to compile SCSS

I then encountered some file not found problems:
eg. `Error: File to import not found or unreadable: ../../node_modules/bootstrap/scss/filename`

If I changed the file paths in https://github.com/mozilla/foxlight/blob/master/src/scss/foxlight.scss to 
`@import '../../../bootstrap/scss/filename';` then the errors are gone.

Thoughts? Suggestion?

/cc @gvn @vazquez

**Comment by gvn** [comment]
Hmm. A couple things: It's not really ready for use in our apps yet...is this a prototype?

My guess is that it's a pathing issue. Can you upload your code somewhere for me to take a look?

We'll need to add a pre-compiled version of Foxlight soon so you'd typically just include the compiled CSS in your project instead of compiling Foxlight yourself.

**Comment by gvn** [comment]
Related:  https://github.com/mozilla/foxlight/issues/13

**Comment by mmmavis** [comment]
@gvn 
> Hmm. A couple things: It's not really ready for use in our apps yet...is this a prototype?

Oh yea I totally understand it's still under development.  I just wanted to try it out - https://github.com/mmmavis/mozilla-clubs-resources :hamster:
